# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class McpMsGraph < Formula
  desc "MCP server for Microsoft Graph — Teams chat, Outlook mail, and Calendar"
  homepage "https://github.com/neverprepared/mcp-ms-graph"
  version "0.2.3"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/neverprepared/mcp-ms-graph/releases/download/v0.2.3/mcp-ms-graph_darwin_arm64.tar.gz"
    sha256 "339765bd2895858093b503b2548da242f7dd9222e538f32c24d6c30cb586f543"

    define_method(:install) do
      bin.install "mcp-ms-graph"
    end
  end

  def caveats
    <<~EOS
      Before first use, run the setup wizard:
        mcp-ms-graph setup

      Then configure your MCP host (e.g. Claude Code) to run:
        mcp-ms-graph
    EOS
  end
end
