# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class McpSlack < Formula
  desc "MCP server for Slack — messages, channels, users, files, reactions, pins, and search"
  homepage "https://github.com/neverprepared/mcp-slack"
  version "0.1.1"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/neverprepared/mcp-slack/releases/download/v0.1.1/mcp-slack_darwin_arm64.tar.gz"
    sha256 "057a967f2e3ecd6f461b75c94754962007322164f221adf9165abf61997d4e27"

    define_method(:install) do
      bin.install "mcp-slack"
    end
  end

  def caveats
    <<~EOS
      Before first use, run the setup wizard:
        mcp-slack setup

      Then configure your MCP host (e.g. Claude Code) to run:
        mcp-slack
    EOS
  end
end
