# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class McpMsGraph < Formula
  desc "MCP server for Microsoft Graph — Teams chat, Outlook mail, and Calendar"
  homepage "https://github.com/neverprepared/mcp-ms-graph"
  version "0.2.1"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/neverprepared/mcp-ms-graph/releases/download/v0.2.1/mcp-ms-graph_darwin_arm64.tar.gz"
    sha256 "11bc2674cdcb9321a5e9ffa1d71df95a0062b7ef3d4b268c0bf3d07c9032868a"

    define_method(:install) do
      bin.install "mcp-ms-graph"
    end
  end

  def caveats
    <<~EOS
      Before first use, run the setup wizard:
        mcp-ms-graph setup

      Then configure your MCP host (e.g. Claude Code) to run:
        mcp-ms-graph
    EOS
  end
end
