# typed: false
# frozen_string_literal: true

# Generated by neverprepared/mcp-kroki release workflow. Do not edit by hand.
class McpKroki < Formula
  desc "MCP server: diagram markup -> images via a Kroki instance"
  homepage "https://github.com/neverprepared/mcp-kroki"
  version "1.0.2"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/neverprepared/mcp-kroki/releases/download/v1.0.2/mcp-kroki_darwin_arm64.tar.gz"
    sha256 "ed5d4c1093cd3c38cb55845de8b314e483a93554b0d08eea9d0809f9f13b2777"

    define_method(:install) do
      bin.install "mcp-kroki"
    end
  end

  def caveats
    <<~EOS
      Point KROKI_URL at a shared/central Kroki endpoint (recommended):
        KROKI_URL=http://localhost:18000 mcp-kroki

      Configure your MCP host (e.g. Claude Code) to run:
        mcp-kroki

      If KROKI_URL is unreachable, mcp-kroki falls back to starting a
      local Kroki Docker stack (project: kroki-shared) — requires Docker.
    EOS
  end
end
