# typed: false
# frozen_string_literal: true

# Generated by neverprepared/phantom-brain release workflow.
# Do not edit by hand — changes are overwritten on next release.
class Pbrainctl < Formula
  desc "MCP server + daemon for durable, validated long-term memory (phantom-brain)"
  homepage "https://github.com/neverprepared/phantom-brain"
  version "3.25.0"
  license "MIT"

  # Use `if Hardware::CPU.arm?` (not `on_arm`/`on_intel`): nested
  # on-arch blocks don't register url/sha256 at spec resolution,
  # so brew reports "formula requires at least a URL". This is the
  # GoReleaser-proven pattern (see mcp-slack.rb in the tap).
  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/neverprepared/phantom-brain/releases/download/v3.25.0/pbrainctl_darwin_arm64.tar.gz"
      sha256 "7270171d8242e47d3dc45a484d5e1e792da232fd6923904ab701bdceecd49abf"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/neverprepared/phantom-brain/releases/download/v3.25.0/pbrainctl_linux_amd64.tar.gz"
      sha256 "699ebc96bcefcde487665c78f16d077a6d43ca51f6bbb79203c6228b0644192f"
    end
    if Hardware::CPU.arm?
      url "https://github.com/neverprepared/phantom-brain/releases/download/v3.25.0/pbrainctl_linux_arm64.tar.gz"
      sha256 "6d6a6bfc75c27f2909eef90c6996fd5f71ee078d8bfaa3969d0d0273c53d0b3c"
    end
  end

  def install
    bin.install "pbrainctl"
  end

  def caveats
    <<~CAVEAT
      pbrainctl is two roles in one binary — agent (`pbrainctl client mcp`)
      and daemon (`pbrainctl server serve`). For the agent, point your
      MCP host at it via .claude.json (or equivalent). For the daemon, set:

        PHANTOM_BRAIN_CONFIG_DIR  (default: ~/.config/phantom-brain-server)
        PHANTOM_BRAIN_DATA_DIR    (default: ~/.local/share/phantom-brain-server)

      then `pbrainctl server serve`. See:
        https://github.com/neverprepared/phantom-brain#setup
    CAVEAT
  end

  test do
    system "#{bin}/pbrainctl", "client", "version"
  end
end
