# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pbrainctl < Formula
  desc "phantom-brain (pbrain) — MCP server + daemon for durable, validated long-term memory"
  homepage "https://github.com/neverprepared/mcp-phantom-brain"
  version "2.3.1"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/neverprepared/mcp-phantom-brain/releases/download/v2.3.1/pbrainctl_darwin_arm64.tar.gz"
    sha256 "165af6c7592a7b8cf2e1c3c875e601951e1b5361756fff031c2de9b378696340"

    define_method(:install) do
      bin.install "pbrainctl"
    end
  end

  def caveats
    <<~EOS
      pbrainctl is two binaries in one — agent (`pbrainctl mcp`) and
      daemon (`pbrainctl serve`). For the agent, point your MCP host
      at it via .claude.json (or equivalent). For the daemon, set:

        PHANTOM_BRAIN_CONFIG_DIR  (default: ~/.config/phantom-brain-server)
        PHANTOM_BRAIN_DATA_DIR    (default: ~/.local/share/phantom-brain-server)

      then `pbrainctl serve`. See:
        https://github.com/neverprepared/mcp-phantom-brain#setup
    EOS
  end
end
