# typed: false
# frozen_string_literal: true

# Generated by neverprepared/phantom-brain release workflow.
# Do not edit by hand — changes are overwritten on next release.
class Pbrainctl < Formula
  desc "MCP server + daemon for durable, validated long-term memory (phantom-brain)"
  homepage "https://github.com/neverprepared/phantom-brain"
  version "3.23.0"
  license "MIT"

  # Use `if Hardware::CPU.arm?` (not `on_arm`/`on_intel`): nested
  # on-arch blocks don't register url/sha256 at spec resolution,
  # so brew reports "formula requires at least a URL". This is the
  # GoReleaser-proven pattern (see mcp-slack.rb in the tap).
  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/neverprepared/phantom-brain/releases/download/v3.23.0/pbrainctl_darwin_arm64.tar.gz"
      sha256 "f0d3f4660b47ccb90b650aeec44548f5fbef968cb8ae7ad43c694843bc1487da"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/neverprepared/phantom-brain/releases/download/v3.23.0/pbrainctl_linux_amd64.tar.gz"
      sha256 "2b133e0f4c49e19b60ae903b48e2ef6e928ee48855ca28f04fc8da4b2a5ecaef"
    end
    if Hardware::CPU.arm?
      url "https://github.com/neverprepared/phantom-brain/releases/download/v3.23.0/pbrainctl_linux_arm64.tar.gz"
      sha256 "8c7b9f3c436ffe5a6b55e81c05b718699fdfe200196d26da8c3615459d03086e"
    end
  end

  def install
    bin.install "pbrainctl"
  end

  def caveats
    <<~CAVEAT
      pbrainctl is two roles in one binary — agent (`pbrainctl client mcp`)
      and daemon (`pbrainctl server serve`). For the agent, point your
      MCP host at it via .claude.json (or equivalent). For the daemon, set:

        PHANTOM_BRAIN_CONFIG_DIR  (default: ~/.config/phantom-brain-server)
        PHANTOM_BRAIN_DATA_DIR    (default: ~/.local/share/phantom-brain-server)

      then `pbrainctl server serve`. See:
        https://github.com/neverprepared/phantom-brain#setup
    CAVEAT
  end

  test do
    system "#{bin}/pbrainctl", "client", "version"
  end
end
