# typed: false
# frozen_string_literal: true

# Generated by neverprepared/prouterctl release workflow.
# Do not edit by hand — changes are overwritten on next release.
class Prouterctl < Formula
  desc "Thin CLI client for the phantom-router orchestration API"
  homepage "https://github.com/neverprepared/prouterctl"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/neverprepared/prouterctl/releases/download/v0.2.0/prouterctl_darwin_arm64.tar.gz"
      sha256 "3163f2eec357f1aecfa469b57b66a6d31f8b37545af6efc2988efa21b7bf7656"
    end
    if Hardware::CPU.intel?
      url "https://github.com/neverprepared/prouterctl/releases/download/v0.2.0/prouterctl_darwin_amd64.tar.gz"
      sha256 "90ee3bec437a687c611f4aafbe2a487b8b4ec8f9ab5c0adafaa185ba9fe068df"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/neverprepared/prouterctl/releases/download/v0.2.0/prouterctl_linux_amd64.tar.gz"
      sha256 "72a298f924eabeb623bd708da2b3a7a33a192016af93a11fc2c4d34eec43f037"
    end
    if Hardware::CPU.arm?
      url "https://github.com/neverprepared/prouterctl/releases/download/v0.2.0/prouterctl_linux_arm64.tar.gz"
      sha256 "ca4c6bda7f306005eb1f40ae3e0f22d3b5a8b55ae5fb3656035b1c07ba17b917"
    end
  end

  def install
    bin.install "prouterctl"
  end

  test do
    system "#{bin}/prouterctl", "version"
  end
end
