# typed: false
# frozen_string_literal: true

# Generated by neverprepared/prouterctl release workflow.
# Do not edit by hand — changes are overwritten on next release.

require "download_strategy"

# Download a release asset from a PRIVATE GitHub repo. The plain
# github.com/.../releases/download/... URL 404s for private repos (it needs a
# web session, not a token), so resolve the asset id via the API and pull the
# api.github.com/.../releases/assets/<id> endpoint with Accept: octet-stream +
# the HOMEBREW_GITHUB_API_TOKEN. The built-in strategy of this name was removed
# from Homebrew, so it is vendored here.
class GitHubPrivateRepositoryReleaseDownloadStrategy < CurlDownloadStrategy
  require "utils/github"

  def initialize(url, name, version, **meta)
    super
    parse_url_pattern
    set_github_token
  end

  def parse_url_pattern
    url_pattern = %r{https://github.com/([^/]+)/([^/]+)/releases/download/([^/]+)/(\S+)}
    match = @url.match(url_pattern)
    raise CurlDownloadStrategyError, "Invalid URL pattern for GitHub Release: #{@url}" if match.nil?

    _, @owner, @repo, @tag, @filename = *match
  end

  def download_url
    "https://api.github.com/repos/#{@owner}/#{@repo}/releases/assets/#{asset_id}"
  end

  private

  def _fetch(url:, resolved_url:, timeout:)
    curl_download(
      download_url,
      "--header", "Accept: application/octet-stream",
      "--header", "Authorization: token #{@github_token}",
      to:          temporary_path,
      try_partial: @try_partial,
      timeout:     timeout
    )
  end

  def set_github_token
    @github_token = ENV.fetch("HOMEBREW_GITHUB_API_TOKEN", nil)
    return if @github_token.present?

    raise CurlDownloadStrategyError, "HOMEBREW_GITHUB_API_TOKEN is required for #{@owner}/#{@repo}."
  end

  def asset_id
    @asset_id ||= begin
      metadata = GitHub::API.open_rest("https://api.github.com/repos/#{@owner}/#{@repo}/releases/tags/#{@tag}")
      asset = metadata.fetch("assets", []).find { |a| a["name"] == @filename }
      raise CurlDownloadStrategyError, "Asset #{@filename} not found in #{@owner}/#{@repo}@#{@tag}." if asset.nil?

      asset.fetch("id")
    end
  end
end

class Prouterctl < Formula
  desc "Thin CLI client for the phantom-router orchestration API"
  homepage "https://github.com/neverprepared/prouterctl"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/neverprepared/prouterctl/releases/download/v0.2.0/prouterctl_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "3163f2eec357f1aecfa469b57b66a6d31f8b37545af6efc2988efa21b7bf7656"
    end
    if Hardware::CPU.intel?
      url "https://github.com/neverprepared/prouterctl/releases/download/v0.2.0/prouterctl_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "90ee3bec437a687c611f4aafbe2a487b8b4ec8f9ab5c0adafaa185ba9fe068df"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/neverprepared/prouterctl/releases/download/v0.2.0/prouterctl_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "72a298f924eabeb623bd708da2b3a7a33a192016af93a11fc2c4d34eec43f037"
    end
    if Hardware::CPU.arm?
      url "https://github.com/neverprepared/prouterctl/releases/download/v0.2.0/prouterctl_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "ca4c6bda7f306005eb1f40ae3e0f22d3b5a8b55ae5fb3656035b1c07ba17b917"
    end
  end

  def install
    bin.install "prouterctl"
  end

  test do
    assert_match "prouterctl", shell_output("#{bin}/prouterctl --help 2>&1")
  end
end
