# typed: false
# frozen_string_literal: true

# Generated by neverprepared/prouterctl release workflow.
# Do not edit by hand — changes are overwritten on next release.
class Prouterctl < Formula
  desc "Thin CLI client for the phantom-router orchestration API"
  homepage "https://github.com/neverprepared/prouterctl"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/neverprepared/prouterctl/releases/download/v0.1.0/prouterctl_darwin_arm64.tar.gz"
      sha256 "cf4746364cb6f4f9e8246e313de3a9c899a358f7e2207b7399be22378249fbcb"
    end
    if Hardware::CPU.intel?
      url "https://github.com/neverprepared/prouterctl/releases/download/v0.1.0/prouterctl_darwin_amd64.tar.gz"
      sha256 "ab43e51a382f5d61bb10f07006308aa6378fbc10d7076dc6563cebb2799933b0"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/neverprepared/prouterctl/releases/download/v0.1.0/prouterctl_linux_amd64.tar.gz"
      sha256 "51c2fd5dc12d8d207d183cb2dc9e42c4af76cb49b523570f4092e401e53df45f"
    end
    if Hardware::CPU.arm?
      url "https://github.com/neverprepared/prouterctl/releases/download/v0.1.0/prouterctl_linux_arm64.tar.gz"
      sha256 "5e0bbe67824f532dcf45af6f9f8fcba4073fb86048042355eef6bfacba8394af"
    end
  end

  def install
    bin.install "prouterctl"
  end

  test do
    system "#{bin}/prouterctl", "version"
  end
end
